### ISSUE TITLE
connection pool

### ISSUE THREAD

**Issue by GurdeepSS** [rizidoro/camus#11]
is there any way to configure connection pool etc in this? if yes how to configure it.

**Comment by izidorome** [comment]
Hello @GurdeepSS,

I apologize for the delayed response.

This package is based on the [Aurora Serverless Data API](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/data-api.html), which automatically manages connection pools for you. If you are not using the RDS Data API, I recommend considering the [RDS Data Proxy](https://aws.amazon.com/rds/proxy/) as an alternative. This is a connection pool service offered by AWS that may be more suitable for your needs.

Hope that helps!
